### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Undefined constant 'Artisan\Console\Commands\Hello'

### ISSUE THREAD

**Issue by tylunari** [moon0326/artisan#7]
Hey I followed your usage guide but I've ran into this error and it's confused me a bit:

```php
PHP Fatal error:  Uncaught Error: Undefined constant 'Artisan\Console\Commands\Hello' in C:\xampp\AlbertoCM\artisan-config.php:5
Stack trace:
#0 C:\xampp\AlbertoCM\vendor\moon\artisan\src\Console\Kernel.php(28): require_once()
#1 C:\xampp\AlbertoCM\artisan(48): Moon\Artisan\Console\Kernel->__construct(Object(Moon\Artisan\Stub\Application), Object(Moon\Artisan\Stub\Dispatcher))
#2 {main}
  thrown in C:\xampp\AlbertoCM\artisan-config.php on line 5

Fatal error: Uncaught Error: Undefined constant 'Artisan\Console\Commands\Hello' in C:\xampp\AlbertoCM\artisan-config.php:5
Stack trace:
#0 C:\xampp\AlbertoCM\vendor\moon\artisan\src\Console\Kernel.php(28): require_once()
#1 C:\xampp\AlbertoCM\artisan(48): Moon\Artisan\Console\Kernel->__construct(Object(Moon\Artisan\Stub\Application), Object(Moon\Artisan\Stub\Dispatcher))
#2 {main}
  thrown in C:\xampp\AlbertoCM\artisan-config.php on line 5
```

My artisan-config.php is: 
```php 
return [
    'commands' => [
        Artisan\Console\Commands\Hello
    ],
];
```

Any idea's on how to fix?

**Comment by tylunari** [comment]
Ignore this, I forgot `'` on the command in the config
